### PR TITLE
Improve controllers

### PR DESCRIPTION
**Pull request by ihor-sviziev**

### CODE REVIEW

**Review by dborishansky — COMMENTED** [review]
This looks good. Please merge and release.

**Comment by ihor-sviziev** [comment]
@dborishansky  any updates?

**Comment by serzhik** [comment]
It is preferred to implement \Magento\Framework\App\Action\Http*ActionInterface instead of extending \Magento\Framework\App\Action\Action

More info: https://community.magento.com/t5/Magento-DevBlog/Decomposition-of-Magento-Controllers/ba-p/430883

**Comment by ihor-sviziev** [comment]
Looks like you just don't want to check it

**Pull request closed without merging**
