### PR TITLE
Add missing Magento core modules in sequence

### PR DESCRIPTION
**Pull request by Tjitse-E**

### CODE REVIEW

**Comment by Tjitse-E** [comment]
@remstone7 could you have a look at this?

**Comment by remstone7** [comment]
i'll look at this for 2.1.0 which we should get out this week - looks fine just will test

**Comment by remstone7** [comment]
adding it to: https://github.com/klaviyo/magento2-klaviyo/pull/100

**Comment by njparadis** [comment]
This fix was merged in #100 and packaged with [2.1.0](https://github.com/klaviyo/magento2-klaviyo/blob/2.1.0/etc/module.xml) - closing this PR for now.

**Pull request closed without merging**
