### PR TITLE
Update system.xml

### PR DESCRIPTION
**Pull request by DomPixie**
Don't put Klaviyo above important core items

## Description
It's being nice to other developers and the Magento team

1.

## Pre-Submission Checklist:

- [ ] You've updated the CHANGELOG following the steps [here](https://github.com/klaviyo/magento2-klaviyo#making-updates)
- [ ] **Internal Only** - If this is a release, please confirm the following:
  - [ ] The links in the changelog have been updated to point towards the new versions
  - [ ] The version has been incremented in the following places: module.xml and composer.json

**NOTE:** Please use the [Changelogger](https://pypi.org/project/changelogged/) cli tool to manage versioned file upgrades.

### CODE REVIEW

**Comment by chavesj** [comment]
@DomPixie How was this tested? Please provide more information re: your validation of these changes, including but not limited to a screenshot of the settings / config page

**Comment by DomPixie** [comment]
@chavesj 

This stops klaviyo becoming default under Stores > Settings > Configuration

image

Default
image

**Review by chavesj — APPROVED** [review]

**Review by chavesj — CHANGES_REQUESTED** [review]
Please update the CHANGELOG

**Review by chavesj — APPROVED** [review]
Please update the CHANGELOG

**Pull request merged**
