### PR TITLE
Add corresponding permissions to Web API resources

### PR DESCRIPTION
**Pull request by ihor-sviziev**
Make all API routes available only when you have needed permissions

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Hi @remstone7,
Could you review my PR?

**Comment by ihor-sviziev** [comment]
Hi @remstone7 @njparadis,
Could you review and merge this Pull Request?

**Comment by remstone7** [comment]
Yes, on our next release which should be in the coming week or 2

**Comment by ihor-sviziev** [comment]
@remstone7 any updates?

**Comment by remstone7** [comment]
@ihor-sviziev we will merge with #54

**Comment by ihor-sviziev** [comment]
@remstone7 still not merged.

**Pull request merged**
